pipeline {
    agent {
        docker {
            image 'node:9.4-alpine'
            args '-p 3334:3334'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('READY') {
            steps {
                sh 'npm install -g yarn'
                sh 'git clone ssh://git@repo.miraco.io/mir/deploy-staging.git'
            }
        }
        stage('Build') {
            steps {
                sh 'yarn && yarn run build'
            }
        }
        stage('Deploy') {
            steps {
                sh 'cp -rf build ./deploy-staging/nft-admin-portal'
                sh "cd ./deploy-staging && git add . && git commit -m 'deploy' && git push origin master"
            }
        }
    }
}
