export default {
  REDIS_HASH_KEY_METAMASK_NONCE: 'RHKMN',

  USER_ROLE_BRAND: 'BRAND',
  USER_ROLE_ENDUSER: 'ENDUSER',
  USER_ROLE_ADMIN: 'ADMIN',

  USER_PERMISSION_TOKEN_ISSUE: 'TOKEN_ISSUE',

  ORDER_TYPE_BRAND_MINT_TOKEN: 'TOKEN_MINT'
}